#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
POC Name  :  埃森诺网络服务质量检测系统 Struts 2命令执行 

 
"""
import urlparse
 

def assign(service, arg):
    if service == 'acsno':
        arr = urlparse.urlparse(arg)
        return True, '%s://%s/' % (arr.scheme, arr.netloc)
def audit(arg):
    param_data = 'usercfg/user_loginUI.do'
    url = arg + param_data
    task_push('struts' ,url)
   

if __name__ == '__main__':
    from dummy import *
    audit(assign('acsno', 'url')[1]) #  
    
